refactor: port tensorflow model to pytorch
fcossio/FiberDiameter pull request #7
Opened 2022-09-28 19:13 UTC by aledelunap

The pytorch port includes the following:
- dataset.py -> Dataset implementation with pytorch lightning 
- model.py -> UNet implementation with pytorch lightning. The LWBNA UNet implementation is pending, the current pull request includes a submodule for the UNet architecture
- training.py -> Training stage with pytorch lightning, model is saved as *.pth

2022-09-29 11:01 UTC, fcossio requested changes
Great work! I have left some comments in the files.

Please don't delete the files that are being deleted and put the model and dataloaders inside the dataset and segmentation folders.

2022-09-29 11:01 UTC, fcossio commented on src/dataset.py
> +        y = torch.tensor(y)[None]
I am ignorant of why the None is used. What does it mean?

2022-09-29 11:01 UTC, fcossio commented on src/dataset.py
> +        if file[: len(stage)] == stage and file[-6:] == "params":
Consider using .startswith(stage) and .endswith("params") that are easier to read.

2022-09-29 11:01 UTC, fcossio commented on src/dataset.py
> +def get_fibers_dictionary(data_dir: str, stage: str):
Do I understand correctly that it returns a dictionary mapping the images of a data split? Why is it needed to use a dictionary if the keys are integers?

2022-09-29 11:01 UTC, fcossio commented on src/dataset.py
> +    def __init__(self, stage: str, fiber_dic: dict, data_dir: str):
How is fiber_dict supposed to look like? Maybe add it in the docstring

2022-09-29 11:01 UTC, fcossio commented on src/dataset.py
> +        y = torch.tensor(y)[None]
Why is `[None]` needed?

2022-09-29 11:01 UTC, fcossio commented on src/dataset.py
> +    def train_dataloader(self: pl.LightningDataModule):
I don't think self needs to be typed, as it can be deduced from the class, but maybe I'm wrong?

2022-09-29 11:01 UTC, fcossio commented on src/training.py
> +from dataset import FiberDataModule
Maybe this can go inside the fiberdiameter folder so we can import it as fiberdiameter.dataset and it becomes easier to test in the future

2022-09-29 11:01 UTC, fcossio commented on src/training.py
> +def init_from_valid_args(cls, args):
Curiosity question: what is the use of this module?

2022-09-29 11:01 UTC, fcossio commented on .gitmodules
> +	url = git@github.com:jaxony/unet-pytorch.git
Not v important: Is it possible to specify the hash of the commit hash that is being used?

2022-09-29 11:01 UTC, fcossio commented on pyproject.toml
> +authors = [
please add the required dependencies to the package with

`poetry add <X>` # if it will be used by the package
`poetry add --group dev <X>` # if it will be used for dev only

2022-09-29 13:47 UTC, aledelunap commented on src/dataset.py
> +def get_fibers_dictionary(data_dir: str, stage: str):
the integers are needed in order to use the dataloader directly, so the dictionary keeps track of the mapping between the idx (integer) and the respective image

2022-09-29 13:47 UTC, aledelunap commented on src/dataset.py
> +        if file[: len(stage)] == stage and file[-6:] == "params":
perfect!

2022-09-29 13:52 UTC, aledelunap commented on src/dataset.py
> +        y = torch.tensor(y)[None]
It just adds a dimension to end up with the shape (1, n, n) to prepare for batching

2022-09-29 14:37 UTC, aledelunap commented on src/dataset.py
> +def get_fibers_dictionary(data_dir: str, stage: str):
I will delete this function, I now see there is no need for a dictionary

2022-09-29 14:38 UTC, aledelunap commented on src/dataset.py
> +    def __init__(self, stage: str, fiber_dic: dict, data_dir: str):
fiber_dict will be removed

2022-09-29 15:51 UTC, aledelunap commented on src/dataset.py
> +        y = torch.tensor(y)[None]
to add an extra dimension for batching (1, n, n), I will refactor it to just move the axis of the original image instead of squeezing it

2022-09-29 21:01 UTC, aledelunap commented on src/dataset.py
> +        y = torch.tensor(y)[None]
This is already answered in another comment.

2022-09-29 21:02 UTC, aledelunap commented on src/training.py
> +def init_from_valid_args(cls, args):
it initializes the class cls with the respective arguments contained in args since the parser receives as input variables for different classes

2022-09-29 21:04 UTC, aledelunap commented on src/dataset.py
> +    def train_dataloader(self: pl.LightningDataModule):
the course types it as such (I don't know if it a standard thing), I can remove it

2022-09-29 21:14 UTC, aledelunap commented on pyproject.toml
> +authors = [
done

2022-09-30 11:12 UTC, fcossio approved these changes
Nice! great first PR

2022-10-01 17:57 UTC, merged